source 'https://rubygems.org'



# Project requirements
gem 'rake'

# Component requirements
gem 'slim'

# Test requirements

# Padrino Stable Gem
gem 'padrino', '0.15.1'

# Or Padrino Edge
# gem 'padrino', :github => 'padrino/padrino-framework'

# Or Individual Gems
# %w(core support gen helpers cache mailer admin).each do |g|
#   gem 'padrino-' + g, '0.12.5'
# end

# Unicorn instead of WEBrick
gem 'unicorn'
